export const ENV_DEFAULTS = {
  NODE_ENV: 'development',
  PORT: 3000,
  DB_HOST: 'localhost',
  DB_PORT: 5432,
  JWT_ACCESS_EXPIRATION: '15m',
  JWT_REFRESH_EXPIRATION: '7d',
  CONFIRMATION_TOKEN_EXPIRATION_HOURS: 1,
  PASSWORD_RESET_TOKEN_EXPIRATION_HOURS: 1,
  APP_URL: 'http://localhost:3000',
  MAIL_HOST: 'mailpit',
  MAIL_PORT: 1025,
  MAIL_FROM: '"StreamTube" <noreply@streamtube.com>',
  SWAGGER_ENABLED: 'false',
  REDIS_HOST: 'localhost',
  REDIS_PORT: 6379,
  MINIO_HOST: 'localhost',
  MINIO_PORT: 9000,
  MINIO_USE_SSL: 'false',
  MINIO_BUCKET: 'streamtube-videos',
} as const;
